#!/usr/bin/env bash

echo "============== Add the functions from scripts/function directory ==============="
. "$GVM_ROOT/scripts/function" || return 1
echo "================================================================================"

function gvm() {
    if [[ "$GVM_ROOT" == "" ]]; then
        display_error "GVM_ROOT not set. Please source \$GVM_ROOT/scripts/gvm"
        return $?
    fi

    if [[ -d $GVM_ROOT/.git ]]; then
        mv "$GVM_ROOT/.git" "$GVM_ROOT/git.bak" ||
            display_error "Failed to move git into out of the way."
    fi

    if [[ ! -d $GVM_ROOT ]]; then
        display_error "GVM_ROOT does not exists. Please reinstall GVM"
        return $?
    fi

	mkdir -p "$GVM_ROOT/logs" > /dev/null 2>&1
	mkdir -p "$GVM_ROOT/gos" > /dev/null 2>&1
	mkdir -p "$GVM_ROOT/archive" > /dev/null 2>&1
	mkdir -p "$GVM_ROOT/archive/package" > /dev/null 2>&1
	mkdir -p "$GVM_ROOT/environments" > /dev/null 2>&1

    if [[ "$1" == "use" ]]; then
        echo "==== use, \$\@ => $@ ===="
        . "$GVM_ROOT/scripts/env/use"
        pwd
        shift
        pwd
        gvm_use "$@"
    elif [[ "$1" == "implode" ]]; then
        echo "====  implode, \$@ => $@  ===="
        . "$GVM_ROOT/scripts/env/implode"
        gvm_implode
    elif [[ "$1" == "pkgset" ]]; then
        echo "====  pkgset, \$@ => $@  ===="
        . "$GVM_ROOT/scripts/env/pkgset-use"
        pwd
        shift
        pwd
        shift
        pwd
        gvm_pkgset_use "$@"
    else
        echo "====  NOT use, implode and pkgset, \$@ => $@ ===="
        "$GVM_ROOT/bin/gvm" "$@"
    fi
}

echo "=============== scripts/env/gvm =============="